-- More Daily Topics: fill politics/economics + fresh prompts everywhere. Idempotent.
insert into public.debate_topics (question, topic_key)
select v.q, v.k from (values
  ('Should the death penalty be abolished?', 'politics-law'),
  ('Should voting be mandatory?', 'politics-law'),
  ('Should the voting age be lowered to 16?', 'politics-law'),
  ('Should the Electoral College be abolished?', 'politics-law'),
  ('Should Supreme Court justices have term limits?', 'politics-law'),
  ('Should the U.S. add more Supreme Court justices?', 'politics-law'),
  ('Should marijuana be legalized federally?', 'politics-law'),
  ('Should all drugs be decriminalized?', 'politics-law'),
  ('Should prisons focus on rehabilitation over punishment?', 'politics-law'),
  ('Should private prisons be banned?', 'politics-law'),
  ('Should felons be allowed to vote?', 'politics-law'),
  ('Should the U.S. abolish the filibuster?', 'politics-law'),
  ('Should gerrymandering be banned?', 'politics-law'),
  ('Should there be term limits for Congress?', 'politics-law'),
  ('Should the U.S. adopt ranked-choice voting?', 'politics-law'),
  ('Should hate speech be protected by free speech laws?', 'politics-law'),
  ('Should the U.S. have open borders?', 'politics-law'),
  ('Should there be a national ID card?', 'politics-law'),
  ('Should police departments be defunded?', 'politics-law'),
  ('Should qualified immunity for police be ended?', 'politics-law'),
  ('Should the U.S. reinstate the military draft?', 'politics-law'),
  ('Should billionaires be allowed to exist?', 'politics-law'),
  ('Should the U.S. adopt a wealth tax?', 'politics-law'),
  ('Should lobbying be banned?', 'politics-law'),
  ('Should campaign donations be capped?', 'politics-law'),
  ('Should the Second Amendment be repealed?', 'politics-law'),
  ('Should the U.S. add statehood for D.C. and Puerto Rico?', 'politics-law'),
  ('Should the government provide universal childcare?', 'politics-law'),
  ('Should churches lose their tax-exempt status?', 'politics-law'),
  ('Should jury duty be optional?', 'politics-law'),
  ('Should the U.S. adopt universal basic income?', 'economics'),
  ('Should the government cap CEO pay?', 'economics'),
  ('Should the U.S. move to a four-day work week?', 'economics'),
  ('Should labor unions have more power?', 'economics'),
  ('Should big banks be broken up?', 'economics'),
  ('Should cryptocurrency be regulated more strictly?', 'economics'),
  ('Should crypto replace traditional currency?', 'economics'),
  ('Should the U.S. return to the gold standard?', 'economics'),
  ('Should inheritance be taxed heavily?', 'economics'),
  ('Should there be nationwide rent control?', 'economics'),
  ('Should housing be a guaranteed human right?', 'economics'),
  ('Should the gig economy be regulated like traditional employment?', 'economics'),
  ('Should student loans be interest-free?', 'economics'),
  ('Should the Federal Reserve be abolished?', 'economics'),
  ('Should the U.S. adopt a flat tax?', 'economics'),
  ('Should offshore tax havens be banned?', 'economics'),
  ('Should companies be required to give workers equity?', 'economics'),
  ('Should there be a maximum wage?', 'economics'),
  ('Should the government subsidize failing industries?', 'economics'),
  ('Should automation that eliminates jobs be taxed?', 'economics'),
  ('Should the U.S. bring back manufacturing at any cost?', 'economics'),
  ('Should landlords be more heavily regulated?', 'economics'),
  ('Should price gouging be illegal during emergencies?', 'economics'),
  ('Should the economy prioritize growth or sustainability?', 'economics'),
  ('Should a college degree be required for most jobs?', 'economics'),
  ('Should countries have the right to seal their borders completely?', 'foreign-policy'),
  ('Should the U.S. remain the world''s police?', 'foreign-policy'),
  ('Should there be a single world government?', 'foreign-policy'),
  ('Should climate refugees be granted automatic asylum?', 'foreign-policy'),
  ('Should wealthy nations pay climate reparations to poorer ones?', 'foreign-policy'),
  ('Should economic sanctions count as acts of war?', 'foreign-policy'),
  ('Should the U.S. cut its defense budget?', 'foreign-policy'),
  ('Should foreign aid be tied to human-rights conditions?', 'foreign-policy'),
  ('Should nuclear-armed states be forced to disarm first?', 'foreign-policy'),
  ('Should international borders ever be redrawn by force?', 'foreign-policy'),
  ('Should global institutions override national sovereignty?', 'foreign-policy'),
  ('Should the U.S. withdraw troops from overseas bases?', 'foreign-policy'),
  ('Should frontier AI development be paused?', 'science-tech'),
  ('Should internet access be a legal right?', 'science-tech'),
  ('Should creating deepfakes be a crime?', 'science-tech'),
  ('Should companies face criminal liability for data breaches?', 'science-tech'),
  ('Should we de-extinct the woolly mammoth?', 'science-tech'),
  ('Should geoengineering be used to fight climate change?', 'science-tech'),
  ('Should gas-powered cars be phased out by law?', 'science-tech'),
  ('Should electric vehicles be mandatory?', 'science-tech'),
  ('Should social media be age-verified by law?', 'science-tech'),
  ('Should we colonize the ocean before space?', 'science-tech'),
  ('Should human cloning research be funded?', 'science-tech'),
  ('Should there be a global ban on lethal autonomous drones?', 'science-tech'),
  ('Is monogamy outdated?', 'culture'),
  ('Should tipping culture be abolished?', 'culture'),
  ('Are open relationships healthier than monogamous ones?', 'culture'),
  ('Is reality TV harmful to society?', 'culture'),
  ('Should we judge historical figures by modern standards?', 'culture'),
  ('Is political correctness good for society?', 'culture'),
  ('Is fandom culture becoming toxic?', 'culture'),
  ('Is fast fashion unethical?', 'culture'),
  ('Should we stop celebrating Columbus Day?', 'culture'),
  ('Are participation trophies bad for kids?', 'culture'),
  ('Should parents monitor their kids'' phones?', 'culture'),
  ('Is homeschooling better than public school?', 'culture'),
  ('Is astrology harmless fun or dangerous nonsense?', 'culture'),
  ('Should influencers disclose every paid promotion?', 'culture'),
  ('Is the pursuit of fame inherently unhealthy?', 'culture'),
  ('Should there be limits on cosmetic surgery?', 'culture'),
  ('Is gaming a legitimate sport?', 'culture'),
  ('Should kids be allowed to specialize in one sport early?', 'culture'),
  ('Is small talk a waste of time?', 'culture'),
  ('Should we abolish the concept of retirement?', 'culture'),
  ('Is beauty objective or subjective?', 'philosophy'),
  ('Does absolute truth exist?', 'philosophy'),
  ('Is human nature fundamentally good or evil?', 'philosophy'),
  ('Can a person ever be truly selfless?', 'philosophy'),
  ('Is forgiveness always the right choice?', 'philosophy'),
  ('Does language shape how we think?', 'philosophy'),
  ('Can a just war exist?', 'philosophy'),
  ('Is patriotism a virtue or a vice?', 'philosophy'),
  ('Do we owe anything to our ancestors?', 'philosophy'),
  ('Is it better to be feared or loved?', 'philosophy'),
  ('Does everyone deserve a second chance?', 'philosophy'),
  ('Is certainty about anything possible?', 'philosophy'),
  ('Should college athletes be paid directly?', 'sports'),
  ('Should college athletes be allowed to unionize?', 'sports'),
  ('Should sports betting be legal everywhere?', 'sports'),
  ('Should performance-enhancing drugs be allowed in pro sports?', 'sports'),
  ('Should there be an enhanced-athletes Olympics?', 'sports'),
  ('Is the designated hitter good for baseball?', 'sports'),
  ('Should fighting be banned in hockey?', 'sports'),
  ('Are sports dynasties good or bad for their leagues?', 'sports'),
  ('Should national teams cap foreign-born players?', 'sports'),
  ('Should the Olympics be held in one permanent location?', 'sports'),
  ('Should esports be in the Olympics?', 'sports'),
  ('Is tanking for draft picks ruining sports?', 'sports'),
  ('Should replay review be reduced in sports?', 'sports'),
  ('Should ties be eliminated from every sport?', 'sports'),
  ('Should athletes stick to sports and stay out of politics?', 'sports')
) as v(q, k)
where not exists (select 1 from public.debate_topics t where t.question = v.q);
