-- Seed the Daily Topics pool across every category. Idempotent — skips
-- any question already present in debate_topics.
insert into public.debate_topics (question, topic_key)
select v.q, v.k
from (values
  ('Should the U.S. continue mass deportations of undocumented immigrants?', 'politics-law'),
  ('Should the U.S. eliminate birthright citizenship?', 'politics-law'),
  ('Should the U.S. adopt universal healthcare?', 'politics-law'),
  ('Should abortion be legal nationwide?', 'politics-law'),
  ('Should the government ban assault weapons?', 'politics-law'),
  ('Are Trump''s tariffs good or bad for Americans?', 'economics'),
  ('Should the government raise taxes on the wealthy?', 'economics'),
  ('Should the federal government forgive student debt?', 'economics'),
  ('Should college be tuition-free?', 'economics'),
  ('Should the minimum wage be raised to $20/hour?', 'economics'),
  ('Is renting better than owning a home?', 'economics'),
  ('Is being rich actually worth sacrificing your 20s?', 'economics'),
  ('Should parents financially support adult children?', 'economics'),
  ('Is college still worth the cost?', 'economics'),
  ('Is the 9-to-5 lifestyle outdated?', 'economics'),
  ('Should people prioritize experiences over saving money?', 'economics'),
  ('Is working from home better for society?', 'economics'),
  ('Is hustle culture a scam?', 'economics'),
  ('Should everyone strive to become financially independent?', 'economics'),
  ('Is living in a major city worth the cost?', 'economics'),
  ('Should the U.S. continue sending military aid to Ukraine?', 'foreign-policy'),
  ('Should the U.S. support Israel militarily?', 'foreign-policy'),
  ('Should the U.S. intervene militarily against Iran?', 'foreign-policy'),
  ('Should Ukraine accept a peace deal that gives up territory?', 'foreign-policy'),
  ('Should Russia be allowed to rejoin the global economy after the war?', 'foreign-policy'),
  ('Should European countries increase military spending?', 'foreign-policy'),
  ('Should NATO expand further?', 'foreign-policy'),
  ('Should Taiwan become independent?', 'foreign-policy'),
  ('Should China invade Taiwan if Taiwan declares independence?', 'foreign-policy'),
  ('Should China be allowed to control the South China Sea?', 'foreign-policy'),
  ('Should India and Pakistan resolve Kashmir through an international agreement?', 'foreign-policy'),
  ('Should Israel accept a two-state solution?', 'foreign-policy'),
  ('Should Palestine be recognized as a sovereign state?', 'foreign-policy'),
  ('Should Iran be allowed to develop nuclear weapons?', 'foreign-policy'),
  ('Should North Korea be offered sanctions relief in exchange for denuclearization?', 'foreign-policy'),
  ('Should countries negotiate with terrorist organizations?', 'foreign-policy'),
  ('Should governments recognize disputed territories as independent countries?', 'foreign-policy'),
  ('Will China become the world''s dominant superpower?', 'foreign-policy'),
  ('Should China and Taiwan reunify?', 'foreign-policy'),
  ('Should Taiwan declare independence?', 'foreign-policy'),
  ('Should other countries defend Taiwan militarily?', 'foreign-policy'),
  ('Should China be allowed to expand its influence in Africa?', 'foreign-policy'),
  ('Should Western countries economically decouple from China?', 'foreign-policy'),
  ('Is China''s Belt and Road Initiative beneficial or exploitative?', 'foreign-policy'),
  ('Should China have greater influence over international institutions?', 'foreign-policy'),
  ('Should Europe become militarily independent from the U.S.?', 'foreign-policy'),
  ('Should the EU become a federal country?', 'foreign-policy'),
  ('Should Ukraine join the EU?', 'foreign-policy'),
  ('Should Turkey join the European Union?', 'foreign-policy'),
  ('Should the EU accept more immigrants?', 'foreign-policy'),
  ('Should Europe create a unified military?', 'foreign-policy'),
  ('Should European countries recognize Palestine?', 'foreign-policy'),
  ('Should the EU impose stronger sanctions on Russia?', 'foreign-policy'),
  ('Should Scotland become independent?', 'foreign-policy'),
  ('Should Catalonia become independent?', 'foreign-policy'),
  ('Should Kashmir become independent?', 'foreign-policy'),
  ('Should India and Pakistan normalize relations?', 'foreign-policy'),
  ('Should India become a permanent member of the U.N. Security Council?', 'foreign-policy'),
  ('Should India align more closely with the West or remain non-aligned?', 'foreign-policy'),
  ('Should Pakistan receive international military assistance?', 'foreign-policy'),
  ('Should countries intervene in territorial disputes between India and Pakistan?', 'foreign-policy'),
  ('Should Mexico militarize its border with the U.S.?', 'foreign-policy'),
  ('Should Latin American countries form a political union?', 'foreign-policy'),
  ('Should Venezuela''s government be internationally recognized?', 'foreign-policy'),
  ('Should other countries intervene in Venezuela''s political crisis?', 'foreign-policy'),
  ('Should Argentina join closer alliances with the West?', 'foreign-policy'),
  ('Should the Falkland Islands/Malvinas belong to Argentina or the UK?', 'foreign-policy'),
  ('Should countries impose sanctions on authoritarian governments in Latin America?', 'foreign-policy'),
  ('Should Latin America reduce its economic dependence on China?', 'foreign-policy'),
  ('Should Cuba''s international sanctions be lifted?', 'foreign-policy'),
  ('Should African countries reduce their dependence on China?', 'foreign-policy'),
  ('Should foreign countries intervene in African civil wars?', 'foreign-policy'),
  ('Should African nations receive reparations for colonialism?', 'foreign-policy'),
  ('Should former colonial powers pay reparations?', 'foreign-policy'),
  ('Should African countries form a stronger political union?', 'foreign-policy'),
  ('Should the African Union have greater authority over member states?', 'foreign-policy'),
  ('Should Western countries intervene to stop military coups?', 'foreign-policy'),
  ('Should African nations prioritize relationships with China, Europe, or the U.S.?', 'foreign-policy'),
  ('Is a two-state solution still possible?', 'foreign-policy'),
  ('Should Palestine be admitted as a full U.N. member?', 'foreign-policy'),
  ('Should Israel and Saudi Arabia normalize relations?', 'foreign-policy'),
  ('Should Iran and Saudi Arabia become strategic partners?', 'foreign-policy'),
  ('Should Gulf countries become militarily independent from Western powers?', 'foreign-policy'),
  ('Should Syria''s government be internationally recognized?', 'foreign-policy'),
  ('Should Turkey play a larger role in Middle Eastern security?', 'foreign-policy'),
  ('Should foreign powers withdraw from Syria?', 'foreign-policy'),
  ('Should all nuclear weapons eventually be eliminated?', 'foreign-policy'),
  ('Does nuclear deterrence actually prevent war?', 'foreign-policy'),
  ('Should countries without nuclear weapons be allowed to develop them?', 'foreign-policy'),
  ('Should Japan develop nuclear weapons?', 'foreign-policy'),
  ('Should South Korea develop nuclear weapons?', 'foreign-policy'),
  ('Should Iran be allowed to have nuclear weapons?', 'foreign-policy'),
  ('Should North Korea be allowed to keep its nuclear arsenal?', 'foreign-policy'),
  ('Is a world with more nuclear powers safer or more dangerous?', 'foreign-policy'),
  ('Should the U.N. have more power over sovereign countries?', 'foreign-policy'),
  ('Should the U.N. Security Council be reformed?', 'foreign-policy'),
  ('Should India receive a permanent Security Council seat?', 'foreign-policy'),
  ('Should Africa receive a permanent Security Council seat?', 'foreign-policy'),
  ('Should the veto power of the five permanent members be abolished?', 'foreign-policy'),
  ('Should the International Criminal Court have greater authority?', 'foreign-policy'),
  ('Should countries be allowed to ignore international courts?', 'foreign-policy'),
  ('Is the United Nations still effective?', 'foreign-policy'),
  ('Should the World Bank forgive developing-country debt?', 'foreign-policy'),
  ('Should the government regulate AI more aggressively?', 'science-tech'),
  ('Has social media made society worse?', 'science-tech'),
  ('Should children under 16 have social media?', 'science-tech'),
  ('Is TikTok destroying attention spans?', 'science-tech'),
  ('Are influencers actually valuable to society?', 'science-tech'),
  ('Should influencers be considered celebrities?', 'science-tech'),
  ('Is becoming an influencer a legitimate career?', 'science-tech'),
  ('Should social media platforms be responsible for misinformation?', 'science-tech'),
  ('Is the internet becoming too sanitized?', 'science-tech'),
  ('Should anonymous accounts be banned?', 'science-tech'),
  ('Is social media destroying authenticity?', 'science-tech'),
  ('Is climate change the biggest threat facing humanity?', 'science-tech'),
  ('Should nuclear power replace fossil fuels?', 'science-tech'),
  ('Is nuclear energy safe enough to expand dramatically?', 'science-tech'),
  ('Should humans genetically engineer embryos?', 'science-tech'),
  ('Should gene editing be used to eliminate genetic diseases?', 'science-tech'),
  ('Should parents be allowed to genetically enhance their children?', 'science-tech'),
  ('Is animal testing justified for medical research?', 'science-tech'),
  ('Should lab-grown meat replace conventional meat?', 'science-tech'),
  ('Is space exploration worth the cost?', 'science-tech'),
  ('Should humans colonize Mars?', 'science-tech'),
  ('Is humanity alone in the universe?', 'science-tech'),
  ('Should we prioritize fixing Earth over colonizing space?', 'science-tech'),
  ('Could humans realistically live to 150?', 'science-tech'),
  ('Should scientists try to resurrect extinct species?', 'science-tech'),
  ('Is nuclear fusion the future of energy?', 'science-tech'),
  ('Should genetic diseases be edited out of human embryos?', 'science-tech'),
  ('Should vaccines ever be mandatory?', 'science-tech'),
  ('Should humans be allowed to clone themselves?', 'science-tech'),
  ('Should organ donors receive financial compensation?', 'science-tech'),
  ('Should lab-grown organs replace organ donation?', 'science-tech'),
  ('Should humans be able to enhance their physical abilities with gene editing?', 'science-tech'),
  ('Should life-extension research be prioritized?', 'science-tech'),
  ('Should psychedelic drugs be legalized for medical treatment?', 'science-tech'),
  ('Should animals have greater legal protections in scientific research?', 'science-tech'),
  ('Is the human brain fundamentally understood?', 'science-tech'),
  ('Will AI ultimately do more good than harm?', 'science-tech'),
  ('Should AI replace human workers?', 'science-tech'),
  ('Should AI-generated art be considered real art?', 'science-tech'),
  ('Should AI companies be allowed to train on copyrighted work?', 'science-tech'),
  ('Should AI-generated content be labeled?', 'science-tech'),
  ('Should governments regulate AI development?', 'science-tech'),
  ('Should AI companies be legally responsible for AI''s decisions?', 'science-tech'),
  ('Could AI become more intelligent than humans?', 'science-tech'),
  ('Should AI be allowed to make life-or-death decisions?', 'science-tech'),
  ('Should AI companions replace some human relationships?', 'science-tech'),
  ('Should governments ban autonomous weapons?', 'science-tech'),
  ('Should people be allowed to create unrestricted AI models?', 'science-tech'),
  ('Will AI create more jobs than it destroys?', 'science-tech'),
  ('Should AI-generated influencers be allowed to make money?', 'science-tech'),
  ('Should AI be allowed to impersonate real people?', 'science-tech'),
  ('Should social media require users to verify their identity?', 'science-tech'),
  ('Should children under 16 be banned from social media?', 'science-tech'),
  ('Should TikTok be banned?', 'science-tech'),
  ('Should social media algorithms be regulated?', 'science-tech'),
  ('Should Big Tech be broken up?', 'science-tech'),
  ('Are tech companies too powerful?', 'science-tech'),
  ('Should companies be allowed to collect behavioral data?', 'science-tech'),
  ('Should targeted advertising be banned?', 'science-tech'),
  ('Should people have the right to completely erase themselves from the internet?', 'science-tech'),
  ('Is privacy more important than personalized technology?', 'science-tech'),
  ('Should self-driving cars replace human drivers?', 'science-tech'),
  ('Who should be responsible when an autonomous car kills someone?', 'science-tech'),
  ('Should autonomous weapons be banned?', 'science-tech'),
  ('Should robots be granted legal rights?', 'science-tech'),
  ('Should Neuralink-style brain implants be legal?', 'science-tech'),
  ('Should humans merge with technology?', 'science-tech'),
  ('Should facial recognition be banned in public spaces?', 'science-tech'),
  ('Should governments have access to encrypted communications?', 'science-tech'),
  ('Should human enhancement technology be available to everyone?', 'science-tech'),
  ('Should we build a permanent human settlement on Mars?', 'science-tech'),
  ('Should transgender athletes compete in women''s sports?', 'culture'),
  ('Is Gen Z actually worse off than previous generations?', 'culture'),
  ('Is social media making people lonelier?', 'culture'),
  ('Are people becoming too easily offended?', 'culture'),
  ('Is cancel culture still a problem?', 'culture'),
  ('Are smartphones destroying social skills?', 'culture'),
  ('Is dating harder than it used to be?', 'culture'),
  ('Are modern friendships becoming less meaningful?', 'culture'),
  ('Is hustle culture toxic?', 'culture'),
  ('Are people too dependent on therapy language?', 'culture'),
  ('Is modern society becoming too individualistic?', 'culture'),
  ('Should couples split everything 50/50?', 'culture'),
  ('Is dating culture worse than it was 20 years ago?', 'culture'),
  ('Should men always pay on the first date?', 'culture'),
  ('Is marriage becoming obsolete?', 'culture'),
  ('Can men and women really be "just friends"?', 'culture'),
  ('Is dating apps making dating worse?', 'culture'),
  ('Should couples share their finances?', 'culture'),
  ('Is cheating ever forgivable?', 'culture'),
  ('Is love enough for a successful marriage?', 'culture'),
  ('Should couples live together before marriage?', 'culture'),
  ('Are celebrities too famous for doing too little?', 'culture'),
  ('Is Hollywood running out of original ideas?', 'culture'),
  ('Are remakes ruining movies?', 'culture'),
  ('Is streaming worse than traditional television?', 'culture'),
  ('Are award shows still relevant?', 'culture'),
  ('Is modern music worse than older music?', 'culture'),
  ('Are influencers replacing traditional celebrities?', 'culture'),
  ('Is celebrity culture unhealthy?', 'culture'),
  ('Should celebrities stay out of politics?', 'culture'),
  ('Is nostalgia ruining entertainment?', 'culture'),
  ('Is hip-hop the greatest music genre?', 'culture'),
  ('Who is the greatest rapper ever?', 'culture'),
  ('Is Taylor Swift overrated?', 'culture'),
  ('Is Kanye West a musical genius?', 'culture'),
  ('Is modern music worse than 2000s music?', 'culture'),
  ('Should artists be separated from their personal behavior?', 'culture'),
  ('Are concerts becoming too expensive?', 'culture'),
  ('Is streaming killing the album?', 'culture'),
  ('Does popularity equal musical quality?', 'culture'),
  ('Is the album format dead?', 'culture'),
  ('Is there such a thing as objective morality?', 'philosophy'),
  ('Do humans have free will?', 'philosophy'),
  ('Does God exist?', 'philosophy'),
  ('What makes someone a good person?', 'philosophy'),
  ('Is it ever morally acceptable to lie?', 'philosophy'),
  ('Is morality more important than happiness?', 'philosophy'),
  ('Is the meaning of life something we discover or create?', 'philosophy'),
  ('Is death necessary for life to have meaning?', 'philosophy'),
  ('Can something be morally right even if it makes people unhappy?', 'philosophy'),
  ('Is ignorance sometimes better than knowledge?', 'philosophy'),
  ('Is it ever okay to sacrifice one person to save five?', 'philosophy'),
  ('Is lying ever morally justified?', 'philosophy'),
  ('Is stealing ever morally justified?', 'philosophy'),
  ('Do intentions matter more than consequences?', 'philosophy'),
  ('Is it wrong to do nothing when you could help someone?', 'philosophy'),
  ('Do we have a moral obligation to help strangers?', 'philosophy'),
  ('Is revenge ever justified?', 'philosophy'),
  ('Can something be legal but still morally wrong?', 'philosophy'),
  ('Is punishment about justice or revenge?', 'philosophy'),
  ('Should criminals always be given a second chance?', 'philosophy'),
  ('Is it morally wrong to bring children into a dangerous world?', 'philosophy'),
  ('Do humans have a moral obligation to future generations?', 'philosophy'),
  ('Is animal suffering morally equal to human suffering?', 'philosophy'),
  ('Is eating meat immoral?', 'philosophy'),
  ('Is extreme wealth inherently unethical?', 'philosophy'),
  ('A runaway train will kill five people — you can pull a lever to divert it toward one. Do you pull it?', 'philosophy'),
  ('Would you push someone off a bridge to save five people?', 'philosophy'),
  ('Would you kill one innocent person to save five?', 'philosophy'),
  ('Would you sacrifice yourself to save five strangers?', 'philosophy'),
  ('Would you sacrifice your child to save five strangers?', 'philosophy'),
  ('Would you sacrifice one loved one to save 1,000 strangers?', 'philosophy'),
  ('Are humans fundamentally different from animals?', 'philosophy'),
  ('Can a machine ever be conscious?', 'philosophy'),
  ('Can consciousness exist without a body?', 'philosophy'),
  ('Is consciousness just brain activity?', 'philosophy'),
  ('Could we ever prove another person is conscious?', 'philosophy'),
  ('Are dreams a form of consciousness?', 'philosophy'),
  ('Does an identical copy of you actually count as you?', 'philosophy'),
  ('If your memories were completely replaced, would you still be you?', 'philosophy'),
  ('If your brain were uploaded to a computer, would you survive?', 'philosophy'),
  ('Could two copies of the same person both genuinely be "you"?', 'philosophy'),
  ('Is artificial intelligence capable of genuine thought?', 'philosophy'),
  ('Can consciousness exist after death?', 'philosophy'),
  ('Are we living in a simulation?', 'philosophy'),
  ('Does reality exist independently of our perception?', 'philosophy'),
  ('Could everything be predetermined?', 'philosophy'),
  ('Does time actually exist?', 'philosophy'),
  ('Could the universe have a purpose?', 'philosophy'),
  ('Why is there something rather than nothing?', 'philosophy'),
  ('Is the universe infinite?', 'philosophy'),
  ('Could there be multiple universes?', 'philosophy'),
  ('Can nothing truly exist?', 'philosophy'),
  ('Is human existence objectively meaningful?', 'philosophy'),
  ('Is happiness the ultimate goal of life?', 'philosophy'),
  ('Would you rather live a short happy life or a long average one?', 'philosophy'),
  ('Is a meaningful life better than a happy life?', 'philosophy'),
  ('Can suffering make life more meaningful?', 'philosophy'),
  ('Is ignorance bliss?', 'philosophy'),
  ('Would you choose to know the exact date of your death?', 'philosophy'),
  ('Would immortality be a blessing or a curse?', 'philosophy'),
  ('If you could eliminate all suffering, should you?', 'philosophy'),
  ('Is it better to live comfortably or pursue greatness?', 'philosophy'),
  ('Should people prioritize happiness or responsibility?', 'philosophy'),
  ('Should individual freedom ever be sacrificed for public safety?', 'philosophy'),
  ('Does society have the right to restrict harmful behavior?', 'philosophy'),
  ('Is equality more important than freedom?', 'philosophy'),
  ('Is economic inequality inherently unjust?', 'philosophy'),
  ('Do people deserve what they earn?', 'philosophy'),
  ('Should everyone have equal outcomes or equal opportunities?', 'philosophy'),
  ('Does government have a moral obligation to provide for its citizens?', 'philosophy'),
  ('Can democracy produce morally wrong decisions?', 'philosophy'),
  ('Should the majority ever be able to override individual rights?', 'philosophy'),
  ('Is civil disobedience morally justified?', 'philosophy'),
  ('Does God need to exist for morality to exist?', 'philosophy'),
  ('Can morality exist without religion?', 'philosophy'),
  ('Can an all-powerful, all-good God coexist with suffering?', 'philosophy'),
  ('Is faith rational?', 'philosophy'),
  ('Can religious belief be justified without evidence?', 'philosophy'),
  ('Does free will exist if God knows everything that will happen?', 'philosophy'),
  ('Would a perfectly good God allow eternal punishment?', 'philosophy'),
  ('Is atheism itself a philosophical position?', 'philosophy'),
  ('Can science and religion answer the same questions?', 'philosophy'),
  ('Is there a rational basis for believing in an afterlife?', 'philosophy'),
  ('Is LeBron the GOAT?', 'sports'),
  ('Is Michael Jordan still the GOAT?', 'sports'),
  ('Is Steph Curry a top 5 player ever?', 'sports'),
  ('Who is the greatest NBA dynasty ever?', 'sports'),
  ('Was Kobe better than LeBron?', 'sports'),
  ('Is the NBA too soft today?', 'sports'),
  ('Should the NBA eliminate the salary cap?', 'sports'),
  ('Is load management ruining basketball?', 'sports'),
  ('Are superteams bad for the NBA?', 'sports'),
  ('Who is the best player in the NBA right now?', 'sports'),
  ('Should the NBA lower the age requirement?', 'sports'),
  ('Is the three-point revolution making basketball worse?', 'sports'),
  ('Is Tom Brady the undisputed GOAT?', 'sports'),
  ('Is Patrick Mahomes on track to surpass Brady?', 'sports'),
  ('Who is the greatest NFL QB ever?', 'sports'),
  ('Are NFL quarterbacks overpaid?', 'sports'),
  ('Is the NFL too pass-heavy?', 'sports'),
  ('Should the NFL eliminate Thursday Night Football?', 'sports'),
  ('Should the NFL expand to 18 games?', 'sports'),
  ('Are NFL referees ruining games?', 'sports'),
  ('Is the NFL''s overtime format fair?', 'sports'),
  ('Which franchise is the greatest NFL dynasty ever?', 'sports'),
  ('Messi vs. Ronaldo — who is the GOAT?', 'sports'),
  ('Is Messi the greatest athlete ever?', 'sports'),
  ('Is the Premier League the best league in the world?', 'sports'),
  ('Should VAR be eliminated?', 'sports'),
  ('Is modern soccer too defensive?', 'sports'),
  ('Should soccer adopt a salary cap?', 'sports'),
  ('Should the World Cup expand further?', 'sports'),
  ('Who is the greatest soccer club ever?', 'sports'),
  ('Is international soccer better than club soccer?', 'sports'),
  ('Should players be allowed to switch national teams?', 'sports'),
  ('Who is the greatest baseball player ever?', 'sports'),
  ('Is Shohei Ohtani the most talented baseball player ever?', 'sports'),
  ('Is the MLB too reliant on analytics?', 'sports'),
  ('Should MLB eliminate the shift restrictions?', 'sports'),
  ('Are baseball games too long?', 'sports'),
  ('Should MLB adopt a salary cap?', 'sports'),
  ('Is the Yankees franchise the greatest in sports?', 'sports'),
  ('Is the Hall of Fame too easy to get into?', 'sports'),
  ('Is Max Verstappen the best driver in the world?', 'sports'),
  ('Hamilton vs. Verstappen — who is better?', 'sports'),
  ('Is F1 becoming too commercialized?', 'sports'),
  ('Should F1 have more races?', 'sports'),
  ('Is the current F1 format actually good racing?', 'sports'),
  ('Should budget caps be eliminated?', 'sports'),
  ('Is F1''s popularity explosion good for the sport?', 'sports'),
  ('Who is the greatest boxer ever?', 'sports'),
  ('Who is the greatest UFC fighter ever?', 'sports'),
  ('Jon Jones vs. Georges St-Pierre — GOAT?', 'sports'),
  ('Is Conor McGregor overrated?', 'sports'),
  ('Is boxing better than MMA?', 'sports'),
  ('Should UFC fighters be paid more?', 'sports'),
  ('Should weight cutting be banned?', 'sports'),
  ('Was Mike Tyson actually an all-time great?', 'sports')
) as v(q, k)
where not exists (select 1 from public.debate_topics t where t.question = v.q);
